name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: request
    attributes:
      label: What should we add/change?
      description: What you’re trying to do + what you’d like to happen.
      placeholder: |
        I’m trying to …

        It would be great if OpenChamber …
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Extra context (optional)
      description: Links, screenshots, mockups, constraints, etc.
